version: "3.8"

services:
  backend:
    build: ./lifechat_backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/casosclinicos
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FRONTEND_URL: http://lifechat.riberadeltajo.es

  frontend:
    build: ./lifechat_frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    depends_on:
      - backend